// ============================================================
// TYPES
// ============================================================

export type RiskLevel = 'critical' | 'high' | 'medium' | 'low';

export type RiskSource = 
  | 'llm'                    // Generated by LLM
  | 'original'               // From original user story
  | 'approved_version'       // From approved story version
  | 'human_modified'         // LLM-generated but human-corrected
  | 'manual';                // Created manually without AI

export type TestDepth = 'comprehensive' | 'thorough' | 'standard' | 'smoke';

export type EffortAllocation = '60%' | '25%' | '10%' | '5%';

// ============================================================
// RISK MODEL
// ============================================================

export interface Risk {
  id: string;
  
  // ── Foreign Keys ──
  user_story_id: string;
  test_plan_id?: string | null;
  
  // ── Computed Properties (from joined UserStory) ──
  user_story_key?: string | null;        // Jira issue key (e.g., PROJ-123)
  user_story_title?: string | null;      // Title of the User Story
  
  // ── Source Traceability ──
  source: RiskSource;
  source_version_id?: string | null;
  source_story_text?: string | null;     // Exact text analyzed
  source_acceptance_criteria?: string | null;  // JSON string of ACs
  
  // ── Probability (1-5) ──
  probability: number;                   // 1-5: How likely is a bug?
  probability_factors?: {                // Detail factors
    complexity?: number;                 // 1-5
    change_rate?: number;                // 1-5
    dev_experience?: number;             // 1-5
    tech_debt?: number;                  // 1-5
  } | null;
  probability_reasoning?: string | null; // Why this P?
  
  // ── Impact (1-5) ──
  impact: number;                        // 1-5: How bad if bug occurs?
  impact_factors?: {                     // Detail factors
    users_affected?: number;             // 1-5
    revenue?: number;                    // 1-5
    safety?: number;                     // 1-5
    reputation?: number;                 // 1-5
  } | null;
  impact_reasoning?: string | null;      // Why this I?
  
  // ── Calculated Score ──
  risk_score: number;                    // P × I (1-25)
  level: RiskLevel;                      // critical | high | medium | low
  
  // ── Risk Description ──
  description: string;                   // What can go wrong?
  mitigation: string | null;             // How to test it?
  reasoning: string | null;              // 3 bullet points explanation
  
  // ── Test Recommendations ──
  test_depth: TestDepth;                 // comprehensive | thorough | standard | smoke
  
  // ── Human Correction Trackinag ──
  is_ai_generated: boolean;              // true = LLM, false = manual
  is_accepted: boolean | null;           // null=pending, true=accepted, false=rejected
  accepted_at?: string | null;           // When accepted/rejected
  corrected_by?: string | null;          // Who corrected it
  corrected_at?: string | null;          // When corrected
  correction_comment?: string | null;    // Reason for correction
  
  // ── Previous Values (for audit trail) ──
  previous_probability?: number | null;  // Before human correction
  previous_impact?: number | null;       // Before human correction
  previous_risk_score?: number | null;   // Before human correction
  previous_level?: RiskLevel | null;     // Before human correction
  
  // ── Timestamps ──
  created_at: string;
  updated_at?: string | null;
}

// ============================================================
// RISK SUMMARY
// ============================================================

export interface RiskSummary {
  total: number;
  by_level: Record<RiskLevel, number>;
  avg_score: number;
  max_score: number;
  min_score: number;
  accepted_count: number;
  rejected_count: number;
  pending_count: number;
  effort_distribution: Record<RiskLevel, string>;
}

// ============================================================
// RISK MATRIX
// ============================================================

export interface RiskMatrixCell {
  row: number;          // Probability row (0-4, where 0=P5)
  col: number;          // Impact column (0-4, where 0=I1)
  level: RiskLevel;
  bgScore: number;      // P × I for this cell
  risks: Risk[];        // Risks in this cell
}

// ============================================================
// CONSTANTS
// ============================================================

export const RISK_LEVEL_CONFIG: Record<RiskLevel, {
  label: string;
  color: string;
  bg: string;
  border: string;
  textClass: string;
  matrixBg: string;
  icon: string;
}> = {
  critical: {
    label: 'Critical',
    color: '#dc2626',       // red-600
    bg: '#fef2f2',          // red-50
    border: '#fca5a5',      // red-300
    textClass: 'level-critical',
    matrixBg: 'rgba(220, 38, 38, 0.85)',
    icon: '🔴',
  },
  high: {
    label: 'High',
    color: '#ea580c',       // orange-600
    bg: '#fff7ed',          // orange-50
    border: '#fdba74',      // orange-300
    textClass: 'level-high',
    matrixBg: 'rgba(234, 88, 12, 0.80)',
    icon: '🟠',
  },
  medium: {
    label: 'Medium',
    color: '#d97706',       // amber-600
    bg: '#fffbeb',          // amber-50
    border: '#fcd34d',      // amber-300
    textClass: 'level-medium',
    matrixBg: 'rgba(217, 119, 6, 0.70)',
    icon: '🟡',
  },
  low: {
    label: 'Low',
    color: '#16a34a',       // green-600
    bg: '#f0fdf4',          // green-50
    border: '#86efac',      // green-300
    textClass: 'level-low',
    matrixBg: 'rgba(22, 163, 74, 0.60)',
    icon: '🟢',
  },
};

// ============================================================
// PROBABILITY BANDS (Document Original: 1-5)
// ============================================================

export const PROB_BANDS = [
  { value: 5, label: 'Almost Certain', sublabel: 'P = 5', description: 'Will almost certainly fail' },
  { value: 4, label: 'Likely',         sublabel: 'P = 4', description: 'Will probably fail' },
  { value: 3, label: 'Possible',       sublabel: 'P = 3', description: 'May fail' },
  { value: 2, label: 'Unlikely',       sublabel: 'P = 2', description: 'Probably won\'t fail' },
  { value: 1, label: 'Rare',           sublabel: 'P = 1', description: 'Almost never fails' },
];

// ============================================================
// IMPACT LEVELS (Document Original: 1-5)
// ============================================================

export const IMPACT_LEVELS = [
  { value: 5, label: 'Critical',  description: 'Business-critical, revenue loss, all users' },
  { value: 4, label: 'Major',     description: 'Significant impact, many users' },
  { value: 3, label: 'Moderate',  description: 'Noticeable impact, some users' },
  { value: 2, label: 'Minor',     description: 'Small impact, few users' },
  { value: 1, label: 'Negligible', description: 'Minimal impact, internal only' },
];

// ============================================================
// TEST DEPTH CONFIG
// ============================================================

export const TEST_DEPTH_CONFIG: Record<TestDepth, {
  label: string;
}> = {
  comprehensive: {
    label: 'Comprehensive'
  },
  thorough: {
    label: 'Thorough'
  },
  standard: {
    label: 'Standard'
  },
  smoke: {
    label: 'Smoke'
  },
};

// ============================================================
// HELPER FUNCTIONS
// ============================================================

/**
 * Classify risk level based on score (Document Original thresholds).
 * Critical: 20-25 | High: 12-19 | Medium: 6-11 | Low: 1-5
 */
export function classifyLevel(score: number): RiskLevel {
  if (score >= 20) return 'critical';
  if (score >= 12) return 'high';
  if (score >= 6) return 'medium';
  return 'low';
}

/**
 * Map probability (1-5) to matrix row (0-4).
 * P=5 → row 0 (top), P=1 → row 4 (bottom)
 */
export function mapProbToRow(p: number): number {
  return 5 - p;
}

/**
 * Map impact (1-5) to matrix column (0-4).
 * I=1 → col 0 (left), I=5 → col 4 (right)
 */
export function mapImpactToCol(i: number): number {
  return i - 1;
}

/**
 * Calculate risk score = P × I
 */
export function calculateRiskScore(probability: number, impact: number): number {
  return probability * impact;
}

/**
 * Get test depth based on risk level
 */
export function getTestDepth(level: RiskLevel): TestDepth {
  const depthMap: Record<RiskLevel, TestDepth> = {
    critical: 'comprehensive',
    high: 'thorough',
    medium: 'standard',
    low: 'smoke',
  };
  return depthMap[level];
}


/**
 * Get color config for a risk level
 */
export function getLevelConfig(level: RiskLevel) {
  return RISK_LEVEL_CONFIG[level];
}

/**
 * Check if a risk is critical (score ≥ 20)
 */
export function isCritical(risk: Risk): boolean {
  return risk.risk_score >= 20;
}

/**
 * Check if a risk is high priority (score ≥ 12)
 */
export function isHighPriority(risk: Risk): boolean {
  return risk.risk_score >= 12;
}

/**
 * Format risk matrix position (e.g., "P4-I5")
 */
export function formatMatrixPosition(probability: number, impact: number): string {
  return `P${probability}-I${impact}`;
}

/**
 * Check if a risk can be modified by human
 */
export function canModify(risk: Risk): boolean {
  return risk.source === 'llm' || risk.source === 'human_modified';
}

/**
 * Get risk summary line (e.g., "[CRITICAL] Payment fails (P4×I5=20)")
 */
export function getRiskSummaryLine(risk: Risk): string {
  return `[${risk.level.toUpperCase()}] ${risk.description} (P${risk.probability}×I${risk.impact}=${risk.risk_score})`;
}