import logging
from typing import Any, Dict, List, Optional

import httpx

from app.core.config import settings

logger = logging.getLogger(__name__)

_BASE = "https://app.testomat.io"


def _enabled() -> bool:
    if not settings.TESTOMATIO_API_KEY:
        logger.warning("[Testomat] TESTOMATIO_API_KEY not set — integration disabled")
        return False
    return True


async def push_test_case(test_case: Any) -> None:
    """Register a newly created test case in Testomat.io.

    Creates a one-time run with status 'skipped' so the test case
    appears in Testomat immediately, before any execution.
    """
    if not _enabled():
        return
    try:
        async with httpx.AsyncClient(timeout=15) as client:
            # 1. Create a run
            r = await client.post(
                f"{_BASE}/api/reporter",
                params={"api_key": settings.TESTOMATIO_API_KEY},
                json={"title": "TestForge AI — Test Cases", "env": "import"},
            )
            logger.info(f"[Testomat] push_test_case create run: {r.status_code} — {r.text}")
            r.raise_for_status()
            uid = r.json().get("uid")
            if not uid:
                logger.warning("[Testomat] No run UID returned")
                return

            # 2. Register the test case (skipped = not yet executed)
            tr = await client.post(
                f"{_BASE}/api/reporter/{uid}/testrun",
                params={"api_key": settings.TESTOMATIO_API_KEY},
                json={
                    "title": test_case.title,
                    "suite_title": "TestForge AI",
                    "status": "skipped",
                    "message": f"Generated by TestForge AI — {test_case.tc_code}",
                    "create": True,
                },
            )
            logger.info(f"[Testomat] push_test_case register: {tr.status_code} — {tr.text}")
            tr.raise_for_status()

            # 3. Finish the run
            fr = await client.put(
                f"{_BASE}/api/reporter/{uid}",
                params={"api_key": settings.TESTOMATIO_API_KEY},
                json={"status_event": "finish"},
            )
            logger.info(f"[Testomat] push_test_case finish: {fr.status_code} — {fr.text}")
            fr.raise_for_status()

            logger.info(f"[Testomat] Test case '{test_case.tc_code}' registered")

    except httpx.HTTPStatusError as e:
        logger.error(f"[Testomat] push_test_case HTTP {e.response.status_code}: {e.response.text}")
    except Exception as e:
        logger.error(f"[Testomat] push_test_case failed: {e}")


async def report_execution(
    tc_code: str,
    title: str,
    status: str,
    browser: str,
    duration: Optional[float],
    steps: List[Dict[str, Any]],
    error_message: Optional[str] = None,
) -> None:
    """Report a Playwright execution result to Testomat.io.

    status must be one of: 'passed' | 'failed'
    """
    if not _enabled():
        return
    try:
        async with httpx.AsyncClient(timeout=15) as client:
            # 1. Create a run
            r = await client.post(
                f"{_BASE}/api/reporter",
                params={"api_key": settings.TESTOMATIO_API_KEY},
                json={"title": f"[{tc_code}] {title}", "env": browser},
            )
            logger.info(f"[Testomat] report_execution create run: {r.status_code} — {r.text}")
            r.raise_for_status()
            uid = r.json().get("uid")
            if not uid:
                logger.warning("[Testomat] No run UID returned")
                return

            # 2. Report test result with step logs
            step_data = [
                {
                    "title": s.get("content", "")[:200],
                    "category": "user",
                    "duration": int((s.get("duration") or 0) * 1000),
                }
                for s in steps[:30]
            ]
            tr = await client.post(
                f"{_BASE}/api/reporter/{uid}/testrun",
                params={"api_key": settings.TESTOMATIO_API_KEY},
                json={
                    "title": title,
                    "suite_title": "TestForge AI",
                    "status": status,
                    "run_time": int((duration or 0) * 1000),
                    "message": error_message or "",
                    "steps": step_data,
                    "create": True,
                },
            )
            logger.info(f"[Testomat] report_execution testrun: {tr.status_code} — {tr.text}")
            tr.raise_for_status()

            # 3. Finish the run
            finish_status = "pass" if status == "passed" else "fail"
            fr = await client.put(
                f"{_BASE}/api/reporter/{uid}",
                params={"api_key": settings.TESTOMATIO_API_KEY},
                json={"status_event": finish_status, "duration": int((duration or 0) * 1000)},
            )
            logger.info(f"[Testomat] report_execution finish: {fr.status_code} — {fr.text}")
            fr.raise_for_status()

            logger.info(f"[Testomat] Execution reported for {tc_code} → {status}")

    except httpx.HTTPStatusError as e:
        logger.error(f"[Testomat] report_execution HTTP {e.response.status_code}: {e.response.text}")
    except Exception as e:
        logger.error(f"[Testomat] report_execution failed: {e}")
