import logging
from typing import Any, Dict, List, Optional

import httpx

from app.core.config import settings

logger = logging.getLogger(__name__)

_BASE = "https://app.testomat.io"


# ── Key helpers ──────────────────────────────────────────────────────────────

def _global_key_enabled() -> bool:
    if not settings.TESTOMATIO_API_KEY:
        return False
    return True


async def validate_api_key(api_key: str) -> bool:
    """
    Validate a Testomat.io API key by attempting to create and immediately
    cancel a test run. Returns True if the key is accepted by Testomat.
    """
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            r = await client.post(
                f"{_BASE}/api/reporter",
                params={"api_key": api_key},
                json={"title": "TestForge AI — key validation", "env": "validation"},
            )
            if r.status_code not in (200, 201):
                return False
            uid = r.json().get("uid")
            if not uid:
                return False
            # Cancel the validation run immediately
            await client.put(
                f"{_BASE}/api/reporter/{uid}",
                params={"api_key": api_key},
                json={"status_event": "skip"},
            )
            return True
    except Exception as exc:
        logger.debug("[Testomat] validate_api_key error: %s", exc)
        return False


# ── Per-user batch push ──────────────────────────────────────────────────────

async def push_test_cases_batch(api_key: str, test_cases: List[Any]) -> Dict[str, Any]:
    """
    Push a list of test case objects to Testomat.io under one run.
    Each test case needs: .title, .tc_code, .gherkin_source (optional).

    Returns: { success: bool, pushed_count: int, error: str | None }
    """
    if not test_cases:
        return {"success": True, "pushed_count": 0, "error": None}

    try:
        async with httpx.AsyncClient(timeout=20) as client:
            # 1. Create a single run for the batch
            r = await client.post(
                f"{_BASE}/api/reporter",
                params={"api_key": api_key},
                json={"title": "TestForge AI — Test Cases", "env": "import"},
            )
            r.raise_for_status()
            uid = r.json().get("uid")
            if not uid:
                return {"success": False, "pushed_count": 0, "error": "No run UID returned by Testomat"}

            # 2. Register each test case in the run
            pushed = 0
            for tc in test_cases:
                suite = getattr(tc, "test_suite_title", None) or "TestForge AI"
                gherkin = getattr(tc, "gherkin_source", "") or ""
                message = (gherkin[:1000] if gherkin else f"Generated by TestForge AI — {tc.tc_code}")
                tr = await client.post(
                    f"{_BASE}/api/reporter/{uid}/testrun",
                    params={"api_key": api_key},
                    json={
                        "title": tc.title,
                        "suite_title": suite,
                        "status": "skipped",
                        "message": message,
                        "create": True,
                    },
                )
                if tr.status_code in (200, 201):
                    pushed += 1
                else:
                    logger.warning(
                        "[Testomat] push_test_cases_batch: TC '%s' returned %d",
                        tc.tc_code, tr.status_code
                    )

            # 3. Finish the run
            await client.put(
                f"{_BASE}/api/reporter/{uid}",
                params={"api_key": api_key},
                json={"status_event": "finish"},
            )

            logger.info("[Testomat] Pushed %d/%d test cases", pushed, len(test_cases))
            return {"success": True, "pushed_count": pushed, "error": None}

    except httpx.HTTPStatusError as e:
        msg = f"HTTP {e.response.status_code}: {e.response.text[:200]}"
        logger.error("[Testomat] push_test_cases_batch failed: %s", msg)
        return {"success": False, "pushed_count": 0, "error": msg}
    except Exception as e:
        logger.error("[Testomat] push_test_cases_batch failed: %s", e)
        return {"success": False, "pushed_count": 0, "error": str(e)}


# ── Legacy: single test-case auto-push (global key, kept for compatibility) ──

async def push_test_case(test_case: Any) -> None:
    """
    Register a single test case using the global TESTOMATIO_API_KEY.
    Only called if a global key is configured.
    """
    if not _global_key_enabled():
        return
    result = await push_test_cases_batch(settings.TESTOMATIO_API_KEY, [test_case])
    if not result["success"]:
        logger.error("[Testomat] Auto-push failed: %s", result["error"])


# ── Execution reporting (unchanged) ─────────────────────────────────────────

async def report_execution(
    tc_code: str,
    title: str,
    status: str,
    browser: str,
    duration: Optional[float],
    steps: List[Dict[str, Any]],
    error_message: Optional[str] = None,
    api_key: Optional[str] = None,
) -> None:
    """
    Report a Playwright execution result to Testomat.io.
    Uses api_key if provided, otherwise falls back to global TESTOMATIO_API_KEY.
    status must be one of: 'passed' | 'failed'
    """
    key = api_key or settings.TESTOMATIO_API_KEY
    if not key:
        return
    try:
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.post(
                f"{_BASE}/api/reporter",
                params={"api_key": key},
                json={"title": f"[{tc_code}] {title}", "env": browser},
            )
            r.raise_for_status()
            uid = r.json().get("uid")
            if not uid:
                return

            step_data = [
                {
                    "title": s.get("content", "")[:200],
                    "category": "user",
                    "duration": int((s.get("duration") or 0) * 1000),
                }
                for s in steps[:30]
            ]
            tr = await client.post(
                f"{_BASE}/api/reporter/{uid}/testrun",
                params={"api_key": key},
                json={
                    "title": title,
                    "suite_title": "TestForge AI",
                    "status": status,
                    "run_time": int((duration or 0) * 1000),
                    "message": error_message or "",
                    "steps": step_data,
                    "create": True,
                },
            )
            tr.raise_for_status()

            finish_status = "pass" if status == "passed" else "fail"
            fr = await client.put(
                f"{_BASE}/api/reporter/{uid}",
                params={"api_key": key},
                json={"status_event": finish_status, "duration": int((duration or 0) * 1000)},
            )
            fr.raise_for_status()
            logger.info("[Testomat] Execution reported for %s → %s", tc_code, status)

    except httpx.HTTPStatusError as e:
        logger.error("[Testomat] report_execution HTTP %d: %s", e.response.status_code, e.response.text)
    except Exception as e:
        logger.error("[Testomat] report_execution failed: %s", e)
