"""add_script_versions_and_test_execution

Revision ID: 9f1ba0651782
Revises: 
Create Date: 2026-04-18 16:37:15.928876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f1ba0651782'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tc_code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('user_story_id', sa.String(length=36), nullable=True),
    sa.Column('user_story_version_id', sa.String(length=36), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('gherkin_source', sa.Text(), nullable=True),
    sa.Column('test_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_results', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('locators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_story_id'], ['user_stories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_story_version_id'], ['user_story_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tc_code')
    )
    op.create_index('idx_test_case_is_active', 'test_cases', ['is_active'], unique=False)
    op.create_index('idx_test_case_tc_code', 'test_cases', ['tc_code'], unique=False)
    op.create_index('idx_test_case_user_story_id', 'test_cases', ['user_story_id'], unique=False)
    op.create_index('idx_test_case_user_story_version_id', 'test_cases', ['user_story_version_id'], unique=False)
    op.create_index(op.f('ix_test_cases_user_story_id'), 'test_cases', ['user_story_id'], unique=False)
    op.create_index(op.f('ix_test_cases_user_story_version_id'), 'test_cases', ['user_story_version_id'], unique=False)
    op.create_table('playwright_script_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('script_content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('validation_status', sa.Enum('NOT_VALIDATED', 'VALID', 'INVALID', name='scriptvalidationstatus'), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), server_default='generated', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_script_version_is_active', 'playwright_script_versions', ['test_case_id', 'is_active'], unique=False)
    op.create_index('idx_script_version_number', 'playwright_script_versions', ['test_case_id', 'version_number'], unique=False)
    op.create_index('idx_script_version_test_case_id', 'playwright_script_versions', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_playwright_script_versions_test_case_id'), 'playwright_script_versions', ['test_case_id'], unique=False)
    op.create_table('test_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('script_version_id', sa.String(length=36), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('browser', sa.String(length=50), server_default='chromium', nullable=False),
    sa.Column('viewport', sa.String(length=20), server_default='1920x1080', nullable=False),
    sa.Column('timeout_ms', sa.Integer(), server_default='30000', nullable=False),
    sa.Column('headless', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('record_video', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('capture_screenshots_on_failure', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='testrunstatus'), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['script_version_id'], ['playwright_script_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_run_script_version_id', 'test_runs', ['script_version_id'], unique=False)
    op.create_index('idx_test_run_started_at', 'test_runs', ['started_at'], unique=False)
    op.create_index('idx_test_run_status', 'test_runs', ['status'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_run_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'ERROR', 'SKIPPED', name='testresultstatus'), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('screenshot_b64', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_result_status', 'test_results', ['status'], unique=False)
    op.create_index('idx_test_result_test_run_id', 'test_results', ['test_run_id'], unique=False)
    op.create_index(op.f('ix_test_results_test_run_id'), 'test_results', ['test_run_id'], unique=True)
    op.create_table('test_step_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_run_id', sa.String(length=36), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('THINK', 'ACT', 'OBSERVE', name='steptype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='stepstatus'), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('screenshot_b64', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_step_result_order', 'test_step_results', ['test_run_id', 'step_order'], unique=False)
    op.create_index('idx_step_result_status', 'test_step_results', ['status'], unique=False)
    op.create_index('idx_step_result_test_run_id', 'test_step_results', ['test_run_id'], unique=False)
    op.create_index('idx_step_result_type', 'test_step_results', ['test_run_id', 'step_type'], unique=False)
    op.create_index(op.f('ix_test_step_results_test_run_id'), 'test_step_results', ['test_run_id'], unique=False)
    op.drop_index(op.f('idx_version_is_customized'), table_name='user_story_versions')
    op.drop_index(op.f('idx_version_story_customized'), table_name='user_story_versions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_version_story_customized'), 'user_story_versions', ['user_story_id', 'is_customized', 'customized_at'], unique=False)
    op.create_index(op.f('idx_version_is_customized'), 'user_story_versions', ['is_customized'], unique=False)
    op.drop_index(op.f('ix_test_step_results_test_run_id'), table_name='test_step_results')
    op.drop_index('idx_step_result_type', table_name='test_step_results')
    op.drop_index('idx_step_result_test_run_id', table_name='test_step_results')
    op.drop_index('idx_step_result_status', table_name='test_step_results')
    op.drop_index('idx_step_result_order', table_name='test_step_results')
    op.drop_table('test_step_results')
    op.drop_index(op.f('ix_test_results_test_run_id'), table_name='test_results')
    op.drop_index('idx_test_result_test_run_id', table_name='test_results')
    op.drop_index('idx_test_result_status', table_name='test_results')
    op.drop_table('test_results')
    op.drop_index('idx_test_run_status', table_name='test_runs')
    op.drop_index('idx_test_run_started_at', table_name='test_runs')
    op.drop_index('idx_test_run_script_version_id', table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index(op.f('ix_playwright_script_versions_test_case_id'), table_name='playwright_script_versions')
    op.drop_index('idx_script_version_test_case_id', table_name='playwright_script_versions')
    op.drop_index('idx_script_version_number', table_name='playwright_script_versions')
    op.drop_index('idx_script_version_is_active', table_name='playwright_script_versions')
    op.drop_table('playwright_script_versions')
    op.drop_index(op.f('ix_test_cases_user_story_version_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_user_story_id'), table_name='test_cases')
    op.drop_index('idx_test_case_user_story_version_id', table_name='test_cases')
    op.drop_index('idx_test_case_user_story_id', table_name='test_cases')
    op.drop_index('idx_test_case_tc_code', table_name='test_cases')
    op.drop_index('idx_test_case_is_active', table_name='test_cases')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
