"""add_notifications_table

Revision ID: ac79303ad538
Revises: 34193ec91697
Create Date: 2026-04-26 15:38:53.856999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac79303ad538'
down_revision: Union[str, Sequence[str], None] = '34193ec91697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_key', sa.String(length=50), nullable=True),
    sa.Column('issue_key', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('jira_comment_posted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('idx_notif_project_key', 'notifications', ['project_key'], unique=False)
    op.create_index('idx_notif_type', 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_project_key'), 'notifications', ['project_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_project_key'), table_name='notifications')
    op.drop_index('idx_notif_type', table_name='notifications')
    op.drop_index('idx_notif_project_key', table_name='notifications')
    op.drop_index('idx_notif_is_read', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
