"""description des changements

Revision ID: b6edd9e1a9a8
Revises: 82fce15fd9b8
Create Date: 2026-04-21 12:30:14.026379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6edd9e1a9a8'
down_revision: Union[str, Sequence[str], None] = '82fce15fd9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_story_versions', 'llm_calls')
    op.drop_column('user_story_versions', 'model_used')
    op.drop_column('user_story_versions', 'completion_tokens')
    op.drop_column('user_story_versions', 'prompt_tokens')
    op.drop_column('user_story_versions', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_story_versions', sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user_story_versions', sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_story_versions', sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_story_versions', sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_story_versions', sa.Column('llm_calls', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
