"""fix_datetime_naive

Revision ID: beac5ba154b7
Revises: b6edd9e1a9a8
Create Date: 2026-04-21 13:11:10.691128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beac5ba154b7'
down_revision: Union[str, Sequence[str], None] = 'b6edd9e1a9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
