"""Pydantic schemas for Risk model - Risk Based Testing (ISTQB)."""

from datetime import datetime
from typing import Optional, List, Dict, Any, Union
from pydantic import BaseModel, Field, field_validator, model_validator


# ============================================================
# BASE SCHEMA
# ============================================================
class RiskBase(BaseModel):
    """Base schema with common attributes aligned with Risk Based Testing document."""

    description: str = Field(
        ..., 
        min_length=3, 
        max_length=5000,
        description="Risk description: what can go wrong? (max 15 words recommended)"
    )
    mitigation: Optional[str] = Field(
        None, 
        max_length=5000,
        description="Testing action to reduce risk (max 12 words recommended)"
    )
    reasoning: Optional[str] = Field(
        None, 
        max_length=10000,
        description="3 bullet points: why P, why I, calculation"
    )
    
    # ── PROBABILITY (Document original: 1-5 scale) ──
    probability: int = Field(
        3, 
        ge=1, 
        le=5,
        description="Probability of failure: 1 (unlikely) to 5 (almost certain)"
    )
    
    # ── PROBABILITY FACTORS ──
    probability_factors: Optional[Dict[str, int]] = Field(
        None,
        description="P sub-factors: {story_complexity, ac_complexity, dependencies, clarity} each 1-5. P = round(avg)."
    )
    probability_reasoning: Optional[str] = Field(
        None,
        description="Why this probability? Explain the factors considered."
    )
    
    # ── IMPACT (Document original: 1-5 scale) ──
    impact: int = Field(
        3, 
        ge=1, 
        le=5,
        description="Impact severity: 1 (minimal) to 5 (business-critical)"
    )
    
    # ── IMPACT FACTORS ──
    impact_factors: Optional[Dict[str, int]] = Field(
        None,
        description="I sub-factors: {users_affected, revenue, safety, reputation} each 1-5. I = round(avg)."
    )
    impact_reasoning: Optional[str] = Field(
        None,
        description="Why this impact? Explain the factors considered."
    )
    
    test_depth: Optional[str] = Field(
        "standard",
        pattern="^(comprehensive|thorough|standard|smoke)$",
        description="Recommended test depth based on risk level"
    )
    
    # ── METADATA ──
    is_ai_generated: bool = Field(
        True,
        description="Was this risk generated by AI/LLM?"
    )
    is_accepted: Optional[bool] = Field(
        None,
        description="Has the QA lead validated this risk? None=pending, True=accepted, False=rejected"
    )
    source: Optional[str] = Field(
        "llm",
        pattern="^(ml|llm|original|approved_version|human_modified|manual)$",
        description="Source of the risk analysis (ml = P/I predicted by the KNN model)"
    )
    
    @field_validator("probability")
    @classmethod
    def validate_probability(cls, v: int) -> int:
        """Probability must be integer between 1 and 5 (document original scale)."""
        if not isinstance(v, int):
            raise ValueError("Probability must be an integer")
        if v < 1 or v > 5:
            raise ValueError("Probability must be between 1 and 5")
        return v
    
    @field_validator("impact")
    @classmethod
    def validate_impact(cls, v: int) -> int:
        """Impact must be integer between 1 and 5 (document original scale)."""
        if not isinstance(v, int):
            raise ValueError("Impact must be an integer")
        if v < 1 or v > 5:
            raise ValueError("Impact must be between 1 and 5")
        return v
    
    def compute_risk_score(self) -> int:
        """
        P × I as per Risk Based Testing document.
        Returns integer 1-25 (NOT float 0.1-4.5).
        """
        return self.probability * self.impact
    
    def compute_level(self) -> str:
        """
        ISTQB 5×5 matrix classification (Score = P × I, range 1-25):
        - Critical : 15-25
        - High     :  9-14
        - Medium   :  4-8
        - Low      :  1-3
        """
        score = self.compute_risk_score()
        if score >= 15:
            return "critical"
        if score >= 9:
            return "high"
        if score >= 4:
            return "medium"
        return "low"
    
    def compute_test_depth(self) -> str:
        """Get recommended test depth based on computed level."""
        depth_map = {
            "critical": "comprehensive",
            "high": "thorough",
            "medium": "standard",
            "low": "smoke"
        }
        return depth_map.get(self.compute_level(), "standard")


# ============================================================
# CREATE / UPDATE SCHEMAS
# ============================================================

class RiskCreate(RiskBase):
    """Schema for creating a new Risk."""

    user_story_id: str = Field(
        ..., 
        min_length=36, 
        max_length=36,
        description="ID of the User Story this risk belongs to"
    )
    test_plan_id: Optional[str] = Field(
        None,
        min_length=36,
        max_length=36,
        description="Optional link to a Test Plan"
    )
    source: Optional[str] = "llm"
    source_version_id: Optional[str] = None
    source_story_text: Optional[str] = Field(
        None,
        description="The exact story text that was analyzed"
    )
    source_acceptance_criteria: Optional[str] = Field(
        None,
        description="JSON string of acceptance criteria used for analysis"
    )


class RiskUpdate(BaseModel):
    """Schema for updating an existing Risk (all fields optional)."""
    
    description: Optional[str] = Field(None, min_length=3, max_length=5000)
    mitigation: Optional[str] = Field(None, max_length=5000)
    reasoning: Optional[str] = Field(None, max_length=10000)
    
    probability: Optional[int] = Field(
        None, 
        ge=1, 
        le=5,
        description="New probability (1-5)"
    )
    impact: Optional[int] = Field(
        None, 
        ge=1, 
        le=5,
        description="New impact (1-5)"
    )
    
    probability_factors: Optional[Dict[str, int]] = None
    probability_reasoning: Optional[str] = None
    impact_factors: Optional[Dict[str, int]] = None
    impact_reasoning: Optional[str] = None
    
    test_depth: Optional[str] = Field(
        None,
        pattern="^(comprehensive|thorough|standard|smoke)$"
    )
    
    is_ai_generated: Optional[bool] = None
    is_accepted: Optional[bool] = None
    source: Optional[str] = None
    
    @field_validator("probability")
    @classmethod
    def validate_probability(cls, v: Optional[int]) -> Optional[int]:
        """Probability must be integer 1-5 if provided."""
        if v is not None:
            if v < 1 or v > 5:
                raise ValueError("Probability must be between 1 and 5")
        return v
    
    @field_validator("impact")
    @classmethod
    def validate_impact(cls, v: Optional[int]) -> Optional[int]:
        """Impact must be integer 1-5 if provided."""
        if v is not None:
            if v < 1 or v > 5:
                raise ValueError("Impact must be between 1 and 5")
        return v


# ============================================================
# RESPONSE SCHEMA
# ============================================================

class RiskResponse(RiskBase):
    """Schema for API responses."""

    id: str
    user_story_id: Optional[str] = None
    test_plan_id: Optional[str] = None
    user_story_key: Optional[str] = Field(
        None,
        description="Jira issue key of the associated User Story"
    )
    user_story_title: Optional[str] = Field(
        None,
        description="Title of the associated User Story"
    )
    risk_score: int = Field(
        ...,
        ge=1,
        le=25,
        description="Risk Score = P × I (1-25)"
    )
    level: str = Field(
        ...,
        pattern="^(critical|high|medium|low)$",
        description="Risk level classification"
    )
    created_at: datetime
    updated_at: Optional[datetime] = None
    source: Optional[str] = "llm"
    source_version_id: Optional[str] = None
    source_story_text: Optional[str] = None
    source_acceptance_criteria: Optional[str] = None
    is_accepted: Optional[bool] = None
    accepted_at: Optional[datetime] = None
    eligible_for_reanalysis: Optional[bool] = None

    class Config:
        from_attributes = True


# ============================================================
# FILTERS & LIST SCHEMAS
# ============================================================

class RiskFilters(BaseModel):
    """Filters for listing risks."""
    
    user_story_id: Optional[str] = None
    level: Optional[str] = Field(
        None, 
        pattern="^(critical|high|medium|low)$",
        description="Filter by risk level"
    )
    is_accepted: Optional[bool] = Field(
        None,
        description="Filter by acceptance status"
    )
    is_ai_generated: Optional[bool] = Field(
        None,
        description="Filter by AI generation status"
    )
    test_depth: Optional[str] = Field(
        None,
        pattern="^(comprehensive|thorough|standard|smoke)$",
        description="Filter by test depth"
    )
    min_risk_score: Optional[int] = Field(
        None, 
        ge=1, 
        le=25,
        description="Minimum risk score (1-25)"
    )
    max_risk_score: Optional[int] = Field(
        None, 
        ge=1, 
        le=25,
        description="Maximum risk score (1-25)"
    )
    source: Optional[str] = Field(
        None,
        pattern="^(ml|llm|original|approved_version|human_modified|manual)$",
        description="Filter by source"
    )


class RiskListResponse(BaseModel):
    """Response for paginated list of risks."""
    
    items: List[RiskResponse]
    total: int
    page: int
    page_size: int
    total_pages: int


# ============================================================
# SUMMARY SCHEMAS
# ============================================================

class RiskLevelCount(BaseModel):
    """Count of risks per level."""
    critical: int = 0
    high: int = 0
    medium: int = 0
    low: int = 0


class RiskSummary(BaseModel):
    """Summary of risk analysis for a project/sprint/epic."""
    
    total: int = Field(..., description="Total number of risks")
    avg_score: int = Field(..., description="Average risk score")
    max_score: int = Field(..., description="Highest risk score")
    min_score: int = Field(..., description="Lowest risk score")
    accepted_count: int = Field(0, description="Number of accepted risks")
    rejected_count: int = Field(0, description="Number of rejected risks")
    pending_count: int = Field(0, description="Number of pending risks")



# ============================================================
# BATCH OPERATIONS
# ============================================================

class RiskBatchCreate(BaseModel):
    """Batch creation of risks for multiple user stories."""
    risks: List[RiskCreate]


class BatchFailedItem(BaseModel):
    """Failed item in batch operation."""
    index: Optional[int] = Field(None, description="Index in the batch")
    issue_key: Optional[str] = Field(None, description="Jira issue key")
    error: str = Field(..., description="Error message")


class RiskBatchResponse(BaseModel):
    """Response for batch operations."""
    
    created: List[RiskResponse] = Field(default_factory=list)
    failed: List[BatchFailedItem] = Field(default_factory=list)
    total_success: int = Field(0, description="Number of successfully created risks")
    total_failed: int = Field(0, description="Number of failed creations")
    
    @property
    def success_rate(self) -> float:
        """Calculate success rate as percentage."""
        total = self.total_success + self.total_failed
        if total == 0:
            return 0.0
        return round(self.total_success / total * 100, 1)