ALLOWED_STANDARD_TERMS = {
    "fr": {
        # Core AC sentence subjects
        "système", "systeme", "utilisateur", "application",
        # Display/output verbs
        "affiche", "afficher", "affiché", "affichage",
        "indique", "indiquer", "indiqué",
        "génère", "genere", "générer", "generer", "généré",
        "montre", "montrer",
        # Prevention/blocking verbs
        "empêche", "empeche", "empêcher", "empêchement",
        "bloque", "bloquer", "bloqué",
        "interdit", "interdire",
        # Permission/action verbs
        "permet", "permettre", "autorise", "autoriser",
        "accède", "accéder", "accès",
        "déclenche", "declenche", "déclencher",
        # State/result verbs
        "valide", "valider", "validé", "validation",
        "enregistre", "enregistrer", "enregistré", "enregistrement",
        "sauvegarde", "sauvegarder", "sauvegardé",
        "conserve", "conserver", "conservé",
        "supprime", "supprimer", "supprimé", "suppression",
        "modifie", "modifier", "modifié", "modification",
        "annule", "annuler", "annulé", "annulation",
        "restaure", "restaurer", "restauré",
        # Connection/auth
        "connexion", "connecte", "connecter", "connecté",
        "déconnexion", "déconnecte", "déconnecter",
        "réussie", "réussi", "réussir",
        "échoue", "échouer", "échec",
        "redirige", "rediriger", "redigé", "redirection",
        "identifiant", "identifiants", "passe", "saisir", "saisie",
        "authentification", "authentifier",
        # Condition/temporal words
        "lorsque", "lorsqu", "après", "avant", "pendant", "dans",
        "moins", "plus", "maximum", "minimum",
        # Data/object nouns
        "message", "messages", "erreur", "erreurs",
        "confirmation", "notification", "avertissement",
        "données", "donnée", "donnees",
        "fichier", "fichiers", "format",
        "champ", "champs", "formulaire",
        "bouton", "liste", "tableau",
        "secondes", "délai",
        "sélectionné", "sélectionner", "sélection",
        "terminé", "terminée", "terminer", "termine",
        # Result/status words
        "succès", "succes", "résultat", "resultat",
        "disponible", "indisponible",
        "compatible", "incompatible",
        "invalide", "incorrect", "correct",
        "obligatoire", "facultatif", "optionnel",
        # Derived action nouns (from verbs)
        "exportation", "importation",
        "opération", "operation",
        "traitement", "processus",
        "synchronisation", "téléchargement",
        "chargement", "création", "création",
        "vérification", "verification",
        # Context/qualifier words
        "contenant", "contient", "contenir",
        "inclut", "inclure", "comprend", "comprendre",
        "détails", "détail", "détaillé", "detaille",
        "raison", "cause", "motif",
        "aucun", "aucune",
        "origine", "source", "destination",
        "exigence", "exigences",
        "lien", "liens", "référence",
        # Network/infra
        "réseau", "reseau", "serveur",
        # Transfer
        "transféré", "transférés", "transférer", "transfert",
        "exporté", "exportés", "exporte", "exporter",
        "importé", "importés", "importe", "importer",
        # UI actions
        "clique", "cliquer", "soumet", "soumettre",
    },
    "en": {
        # Core AC sentence subjects
        "system", "user", "application",
        # Display/output verbs
        "displays", "display", "displayed",
        "shows", "show", "shown",
        "generates", "generate", "generated",
        "indicates", "indicate", "indicated",
        # Prevention/blocking verbs
        "prevents", "prevent", "prevented",
        "blocks", "block", "blocked",
        "prohibits", "prohibit",
        # Permission/action verbs
        "allows", "allow", "allowed",
        "enables", "enable", "enabled",
        "triggers", "trigger", "triggered",
        # State/result verbs
        "validates", "validate", "validated", "validation",
        "saves", "save", "saved", "saving",
        "preserves", "preserve", "preserved",
        "deletes", "delete", "deleted", "deletion",
        "modifies", "modify", "modified", "modification",
        "cancels", "cancel", "cancelled",
        "restores", "restore", "restored",
        # Connection/auth
        "login", "logged", "logs",
        "redirect", "redirects", "redirected", "redirection",
        "credentials", "password", "username",
        "enter", "enters", "entered",
        "authentication", "authenticate",
        "successful", "successfully",
        "failed", "fails", "failure",
        # Condition/temporal words
        "when", "after", "before", "during", "within",
        "less", "more", "maximum", "minimum",
        # Data/object nouns
        "message", "messages", "error", "errors",
        "confirmation", "notification", "warning",
        "data", "field", "fields", "form",
        "button", "dropdown", "table",
        "seconds",
        "selected", "selection",
        "completed", "complete",
        # Result/status words
        "success", "result",
        "available", "unavailable",
        "compatible", "incompatible",
        "invalid", "incorrect", "correct",
        "mandatory", "optional", "required",
        # Derived action nouns
        "operation", "process", "processing",
        "transfer", "transferred",
        "exported", "imported",
        # Context/qualifier words
        "containing", "contains", "includes",
        "details", "detail", "detailed",
        "reason", "cause",
        "origin", "source", "destination",
        "requirement", "requirements",
        "link", "links", "reference",
        # Network/infra
        "network", "server",
        # File
        "file", "files", "format",
        # UI actions
        "click", "clicks", "submit", "submits",
        "access", "accesses",
        "display", "loading",
    }
}

HALLUCINATION_PATTERNS = [
    r"\bmachine learning\b",
    r"\bblockchain\b",
    r"\bai\b",
]

MAX_NEW_DOMAIN_TERMS = 3

FRENCH_STEMS = {
    "connect": ["connecter", "connecte", "connecté", "connexion", "déconnecter", "déconnexion"],
    "affich": ["afficher", "affiche", "affiché", "affichage"],
    "valid": ["valider", "valide", "validé", "validation"],
    "enregistr": ["enregistrer", "enregistre", "enregistré", "enregistrement"],
    "sélection": ["sélectionner", "sélectionne", "sélectionné", "sélection"],
    "redirig": ["rediriger", "redirige", "redigé", "redirection"],
    "export": ["exporter", "exporte", "exporté", "exportés", "exportation"],
    "import": ["importer", "importe", "importé", "importés", "importation"],
    "transf": ["transférer", "transfère", "transféré", "transférés", "transfert"],
    "virem": ["virement", "virements"],
    "paie": ["payer", "paie", "payé", "paiement", "paiements"],
    "supprim": ["supprimer", "supprime", "supprimé", "suppression"],
    "modif": ["modifier", "modifie", "modifié", "modification"],
    "génèr": ["générer", "génère", "généré", "génération"],
    "créa": ["créer", "crée", "créé", "création"],
    "vérif": ["vérifier", "vérifie", "vérifié", "vérification"],
    "empêch": ["empêcher", "empêche", "empêché", "empêchement"],
    "conserv": ["conserver", "conserve", "conservé", "conservation"],
    "termin": ["terminer", "termine", "terminé", "terminée"],
    "indiqu": ["indiquer", "indique", "indiqué", "indication"],
    "synchron": ["synchroniser", "synchronise", "synchronisé", "synchronisation"],
    "notif": ["notifier", "notifie", "notifié", "notification"],
    "confirm": ["confirmer", "confirme", "confirmé", "confirmation"],
    "bloqu": ["bloquer", "bloque", "bloqué", "blocage"],
    "charg": ["charger", "charge", "chargé", "chargement"],
    "déclenck": ["déclencher", "déclenche", "déclenché", "déclenchement"],
    "annul": ["annuler", "annule", "annulé", "annulation"],
    "envoi": ["envoyer", "envoie", "envoyé", "envoi"],
}

ENGLISH_STEMS = {
    "connect": ["connect", "connects", "connected", "connection", "disconnect"],
    "display": ["display", "displays", "displayed", "displaying"],
    "valid": ["validate", "validates", "validated", "validation"],
    "save": ["save", "saves", "saved", "saving"],
    "select": ["select", "selects", "selected", "selection"],
    "redirect": ["redirect", "redirects", "redirected", "redirection"],
    "export": ["export", "exports", "exported", "exporting", "exportation"],
    "import": ["import", "imports", "imported", "importing", "importation"],
    "transfer": ["transfer", "transfers", "transferred", "transferring"],
    "payment": ["pay", "pays", "paid", "payment", "payments"],
    "delet": ["delete", "deletes", "deleted", "deletion"],
    "modif": ["modify", "modifies", "modified", "modification"],
    "generat": ["generate", "generates", "generated", "generation"],
    "creat": ["create", "creates", "created", "creation"],
    "verif": ["verify", "verifies", "verified", "verification"],
    "prevent": ["prevent", "prevents", "prevented", "prevention"],
    "preserv": ["preserve", "preserves", "preserved"],
    "complet": ["complete", "completes", "completed", "completion"],
    "terminat": ["terminate", "terminates", "terminated", "termination"],
    "indicat": ["indicate", "indicates", "indicated", "indication"],
    "notif": ["notify", "notifies", "notified", "notification"],
    "confirm": ["confirm", "confirms", "confirmed", "confirmation"],
    "block": ["block", "blocks", "blocked", "blocking"],
    "trigger": ["trigger", "triggers", "triggered", "triggering"],
    "cancel": ["cancel", "cancels", "cancelled", "cancellation"],
}

SAFE_TERMS = {
    # ───────── FR ─────────
    "afficher", "affiché", "affichage",
    "valider", "valide", "validation",
    "rediriger", "redirige", "redirection",
    "erreur", "message", "connexion",
    "connecte", "connecté", "connecter",
    "saisie", "saisir",
    "chargement",
    # System behavior verbs
    "système", "systeme",
    "génère", "genere", "générer",
    "indique", "indiquer",
    "empêche", "empeche", "empêcher",
    "conserve", "conserver",
    "bloque", "bloquer",
    "déclenche", "déclencher",
    "termine", "terminer", "terminé", "terminée",
    "contenant", "contient", "contenir",
    # Result/status words
    "succès", "échec", "échoue",
    "disponible", "indisponible",
    "détails", "détail", "détaillé",
    "raison", "aucun", "aucune",
    "opération", "processus", "traitement",
    "exportation", "importation",
    "transféré", "transférés", "transfert",
    "exporté", "exportés",
    "réseau", "serveur",
    "origine", "destination",
    "exigence", "exigences",
    "lien", "liens", "référence",
    "notification", "avertissement", "confirmation",

    # ───────── EN ─────────
    "display", "displays", "displayed", "show", "shows",
    "validate", "validates", "validated",
    "redirect", "redirects", "redirected",
    "error", "message",
    "login", "logged", "authentication",
    "input", "enter", "entered",
    "loading",
    # System behavior verbs
    "system",
    "generates", "generate",
    "indicates", "indicate",
    "prevents", "prevent",
    "preserves", "preserve",
    "blocks", "block",
    "triggers", "trigger",
    "completes", "completed", "terminates",
    "contains", "containing",
    # Result/status words
    "success", "failure", "fails",
    "available", "unavailable",
    "details", "detail", "detailed",
    "reason",
    "operation", "process", "processing",
    "transferred", "exported", "imported",
    "network", "server",
    "origin", "destination",
    "requirement", "requirements",
    "link", "links", "reference",
    "notification", "warning", "confirmation",

    # Common UI/action terms that ACs naturally use
    "fichier", "file", "sélectionner", "select", "bouton", "button",
    "format", "supporté", "supported", "refuse", "reject",
    "enregistrer", "save", "confirmation", "erreur", "error",
    "succès", "success", "échoue", "fails", "valide", "valid",
    "invalide", "invalid", "affiche", "displays", "redirige", "redirects",
    "clique", "click", "soumet", "submit", "connexion", "login",
    "identifiants", "credentials", "correct", "incorrect",
}